---
- hosts: all
  become: true
  tasks:
    - name: Display uptime
      shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
      register: hostname
    - debug:
        var: hostname.stdout
